### ISSUE TITLE
[djangoCMS 4.0/3.8] Broken/not working Plugins

### ISSUE THREAD

**Issue by crydotsnake** [django-cms/djangocms-bootstrap4#134]
# What is this issue about?
This issue lists plugins from the djangocms-bootstrap4 package that are broken or not working and have error messages under djangoCMS version 4.

# Broken plugins ive found so far

## Link/Button Plugin

Error message: 
![Bildschirmfoto 2021-04-02 um 20 29 46](https://user-images.githubusercontent.com/39345336/113443387-2bbb5c80-93f2-11eb-91ad-a56ba26e4899.png)

**Comment by crydotsnake** [comment]
## Carousel/Carousel Slide Plugin
- Error when choosing the Carousel Slide Plugin

![Bildschirmfoto 2021-04-03 um 10 23 35](https://user-images.githubusercontent.com/39345336/113472947-a756f100-9466-11eb-973f-59fa49c96be9.png)

## Tabs Plugin
- Tab items are output as a list `<li>`

![Bildschirmfoto 2021-04-03 um 10 44 32](https://user-images.githubusercontent.com/39345336/113473403-9491eb80-9469-11eb-9d85-ce1dd832d2c0.png)

**Comment by sin-ack** [comment]
I believe this is intended. From the README: 
> django CMS Bootstrap 4 **does not** add the styles or javascript files to your frontend, these need to be added at your discretion.

I do agree with this, because otherwise it would get in your way when you want to add Bootstrap 4 yourself (plugin JS/CSS clashing with own assets in the case of bundling). However, `djangocms-installer` should probably set this up for you, as it also installs this package alongside DjangoCMS, and by default it does not add any styles. Maybe something like simple static files containing minified Bootstrap as a first step, which developers can replace with their own custom setup if they need to?

**Comment by crydotsnake** [comment]
Closed the issue because at least it was not a bug with the bootstrap4 package.
