### ISSUE TITLE
Thumbnails in a carousel

### ISSUE THREAD

**Issue by serjflint** [django-cms/djangocms-bootstrap4#37]
I created default carousel. Then I insert carousel slides in it. Pictures in slides are really wide so it is easy to notice any changes. But I got upscaled thumbnails instead of my original pictures. How to put pictures in the carousel as is?

**Comment by vxsx** [comment]
Carousel uses aspect ratios to create thumbnails for images so that all of them are uniform:

![screen shot 2018-07-09 at 06 40 04](https://user-images.githubusercontent.com/366813/42431031-2f376be6-8343-11e8-858a-50fabee00de0.png)

If no aspect ratio is speicified it uses default size for images, which is 1024x768, unless the parent template is wrapped with

```
{% with 1000 as width and 400 as height %}
```

https://github.com/divio/djangocms-bootstrap4/blob/fa1be206f432aa81535da3aef2d231c86ca25e85/djangocms_bootstrap4/contrib/bootstrap4_carousel/constants.py#L30

The easiest solution is to either pick aspect ratio that fits or modify the template to use original pictures. The plugin provides template option for that.

**Comment by mateoreyes** [comment]
how do I modify the template so that it uses the original sizes of the images ?
