### ISSUE TITLE
How do you create a relative link that isn't a CMS page?

### ISSUE THREAD

**Issue by electroniceagle** [django-cms/djangocms-bootstrap4#51]
There are may cases where we'd like to make a link button to relative or absolute path on the same host (i.e. /accounts/signup/) that aren't CMS Pages.  Not sure of the right way to do this.  

EXTERNAL LINK fails with a url validation error and INTERNAL LINK only shows you CMS pages.

Is there a better way to accomplish this? 

![screen shot 2018-07-13 at 12 07 55 pm](https://user-images.githubusercontent.com/219202/42704489-f5c3ca36-869d-11e8-841e-94868f9da9ac.png)

**Comment by filwaitman** [comment]
Hi @electroniceagle !

This is a limitation from [djangocms-link](https://github.com/divio/djangocms-link/blob/master/djangocms_link/models.py#L66) which is based upon a design decision taken by [django itself](https://code.djangoproject.com/ticket/10896).

Is it an option for you to simply add the domain part to the external link (so it is a complete URL instead of a path)?
