### ISSUE TITLE
card_content / card_context is there a typo/autocorrect issue ?

### ISSUE THREAD

**Issue by rolandf** [django-cms/djangocms-bootstrap4#85]
I noticed that some of the plugins defined in djangocms-bootstrap4 have a xxx_content member in the model and a xxx_content.html in the templates such as the carousel one.

For the cards, I see a card_context member in the model and a card_content.html template that doesn't seem to be referenced anywhere.

Is this an error or did I missed something ?

I'm asking because I'm doing my first plugins to create custom navbar and I model it from the card plugin and it seems a bit odd.

**Comment by FinalAngel** [comment]
Hello @rolandf, the card system does not support templates such as the carousel. This was omitted due to the fact that you can build very custom structures with the rudimentary card plugins.

Then you could leverage [djangocms-modules](https://github.com/divio/djangocms-modules) to copy and paste these structures easily :)
